name: Test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12'
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: |
        pip install -r requirements.txt
        python adb.py
        python ./demo.py
